### ISSUE TITLE
Meter alert properties not returned

### ISSUE THREAD

**Issue by pankleks** [keymetrics/pmx#102]
Hi,

I have following meter defined:

```ts
Probe.meter({
    name: "task execution / min",
    samples: 1,
    timeframe: 60,
    alert: {
        mode: "threshold",
        value: 0,
        msg: "no executions",
        cmp: function (v, t) {
            return v <= t;
        },
        func: function () {
            console.error("no executions");
        }
    }
})
```

in my monitoring app, I connect to pm2 and using `pm2.list` I query all processes.

what I get for above meter is:
```js
                    "task execution / min": {
                        "alert": {
                            "cmp": ">",
                            "value": null,
                            "mode": "threshold"
                        },
                        "agg_type": "avg",
                        "value": "0.02"
                    }
```

So, first of all it looks when threshold value is 0, it's converted to null (when setting to 0.1 it's not) -> probably invalid use of `!` somewhere in code:)

But more importantly all my other properties of a meter alert are lost:

- `cmp` function is converted to ">", I was expecting function or function body as a string
- `msg` is lost
- `func` is lost

Without these entire alerting is not really usable by 3'rd party apps.

BTW, is pm2 itself somehow process alters (or it's only used by keymetrics dashboard) - could not find it in any documentation?

Thanks

**Comment by vmarchaud** [comment]
```
But more importantly all my other properties of a meter alert are lost:
```
It's only PMX that handle errors, also note that you cannot serialize function so they are removed when extracting data with `pm2.list`.
```
So, first of all it looks when threshold value is 0, it's converted to null
```
We are aware that the 0 is converted to null. Indded that might be a `!` misplaced

```
BTW, is pm2 itself somehow process alters (or it's only used by keymetrics dashboard) - could not find it in any documentation?
```
Nope, only handled via PMX

```
Without these entire alerting is not really usable by 3'rd party apps.
```
Note that the aim of PMX isn't to have a framework to handle 3rd party's system, it's a library to integrate Keymetrics. So naturally we will not support these use cases.

**Comment by pankleks** [comment]
Thanks for fast response, can you please tell me more about 

> Nope, only handled via PMX

So if I define my meter as above, will pm2 or pmx fire `cmp` / `func` functions?
How can I find (except KM dashboard) that actually there was some alert for a meter?

**Comment by vmarchaud** [comment]
It's pmx that will handle these functions, and you can't find them elsewhere apart keymetrics because pmx will send the alert directly to our agent that will send it to Keymetrics.

**Comment by pankleks** [comment]
ok clear thanks
