### ISSUE TITLE
PMX not registering custom metrics when starting the app with npm start

### ISSUE THREAD

**Issue by AdrienNeveu** [keymetrics/pmx#118]
My app starts with npm start, so I created the file pm2.json:

```
{
    "apps": [
        {
            "name": "myapp",
            "script": "npm",
            "args" : "start"
        }
    ]
}
```

When I start the app with `pm2 start pm2.json`, my custom metrics/errors... aren't registered to keymetrics. When starting with `pm2 start index.js`, it works.

**Comment by Unitech** [comment]
The script needs to be the Node.js application, not npm.

Or in the package.json, the start attribute needs to be pm2 start pm2.json
