### ISSUE TITLE
os.tmpDir() is deprecated. Use os.tmpdir() instead

### ISSUE THREAD

**Issue by joaoritter** [keymetrics/pmx#125]
![image](https://user-images.githubusercontent.com/5597861/41511071-d7888a9e-7224-11e8-8711-79c4d706f8af.png)

I followed these instructions to set up http://docs.keymetrics.io/docs/pages/profiling/

**Comment by wallet77** [comment]
Hi @joaoritter 

Which version of pmx is it ?
I can't see any os.tmpDir in the code on the latest version. We only use os.tmpdir !

**Comment by joaoritter** [comment]
`yarn add pmx@latest` did the trick! I had installed pmx as a dependency when following these instructions http://docs.keymetrics.io/docs/pages/profiling/
