### ISSUE TITLE
How to call action??

### ISSUE THREAD

**Issue by zerataul** [keymetrics/pmx#13]
i made  axm.action
good operation in the keymetrics.io

So i wish call in my server

axm.emit...????

how to call action and reply

axm.action('test', function(reply) {
  console.log('Action test called from external process');
  reply({ res : 'hello moto'});
});

**Comment by jshkurti** [comment]
https://keymetrics.io/assets/images/application-demo.png
Just click on your app name and a button will appear.

**Comment by jshkurti** [comment]
Also, axm is deprecated. Use pmx instead.
https://github.com/keymetrics/pmx

**Comment by zerataul** [comment]
Thank you!!
