### ISSUE TITLE
pmx.emit('label', object) modifies object.

### ISSUE THREAD

**Issue by dkran** [keymetrics/pmx#14]
I was trying to use pmx.emit to log out customer onboards before they are inserted into my database.  
I have json filtering in place so I can insert my req.body directly into the database. I was just doing pmx.emit('customer:creation', req.body), then inserting it into my database. This fails.  If I remove pmx.emit from the equation, it succeeds.  somehow simply logging the object is modifying the object. Bad mojo.

https://github.com/keymetrics/pmx/blob/master/lib/events.js#L14

This is our offending line of code, it apparently appends an __name as the event name to the object, but why is that necessary?  Wouldn't it posit that these objects would be reused later possibly?

**Comment by Unitech** [comment]
We should use json-stringify-safe module to avoid this behaviour

**Comment by dkran** [comment]
So I should just stringify that object huh?  Okay my mistake.

**Comment by Unitech** [comment]
fixed

**Comment by dkran** [comment]
Thank you.
