### ISSUE TITLE
Process disconnected from parent and json type error

### ISSUE THREAD

**Issue by dakisxx** [keymetrics/pmx#16]
Hi,

please take a look at the following:

    server-0 (err): Process disconnected from parent !
    server-0 (err): TypeError: Converting circular structure to JSON
    server-0 (err):     at Object.stringify (native)
    server-0 (err):     at process.target.send (child_process.js:461:23)
    server-0 (err):     at ipcSend (.../node_modules/pmx/lib/utils/transport.js:21:13)
    server-0 (err):     at Object.Transport.send (.../node_modules/pmx/lib/utils/transport.js:32:3)
    server-0 (err):     at process.catchException (.../node_modules/pmx/lib/notify.js:39:15)
    server-0 (err):     at process.g (events.js:180:16)
    server-0 (err):     at process.emit (events.js:95:17)
    server-0 (err):     at process._fatalException (node.js:272:26)
    PM2: 2015-04-20 09:46:33: App closed with code: 1

The `converting circular structure ` error seems to be coming from pmx itself, in `transport.js`

    try {
        process.send(args);
    } catch(e) {
        console.error('Process disconnected from parent !');
        console.error(e.stack || e);
        process.exit(1);
    }

The error that caused this is an `TypeError: undefined is not a function` error

Shouldn't this error get logged to keymetrics instead of pmx itself breaking? The error stack that seems to cause the problem doesn't seem interesting at all, just a normal stack.

**Comment by denistrofimov** [comment]
The same problem

**Comment by stringbeans** [comment]
+1

looks like its related to: https://github.com/keymetrics/pmx/issues/11

**Comment by dakisxx** [comment]
I should note that this has nothing to do with express as it does in #11.  I am certain because I don't use express, only socket.io. 

It is actually very simple in this case.  My code called an undefined function. This caused pmx to break.
