### ISSUE TITLE
Support of koa

### ISSUE THREAD

**Issue by RHavar** [keymetrics/pmx#17]
I gave it a try pmx a try with our  [koa](https://github.com/koajs/koa) server but it doesn't seem to show up in the http routes? Is this something that pmx will or should support

**Comment by AlexeyKhristov** [comment]
+1

**Comment by Unitech** [comment]
we wrap the [http.Server](https://github.com/keymetrics/pmx/blob/master/lib/wrapper/simple_http.js#L31)
it should work with koa seamlessly, is Koa handling [routes differently](https://github.com/keymetrics/pmx/blob/master/lib/wrapper/simple_http.js#L39) ?

**Comment by jshkurti** [comment]
Hi,

Only routes with latency over 200ms and response codes greater than or equal to 500 are logged by default.
You can change this using these params in your pmx.init():

{
    http_latency  : 200, // value in ms
    http_code     : 500, // All transactions where http_code > 500 will be saved
}

**Comment by AlexeyKhristov** [comment]
thanks a lot
