### ISSUE TITLE
PMX Deleting event

### ISSUE THREAD

**Issue by rbarkas** [keymetrics/pmx#19]
How can I delete a custom event that is no longer needed?

**Comment by jorge-d** [comment]
There is no way to manually delete events right now, however you can just stop emitting them and they should be deleted automatically after a certain number of days (the _Persistence_ value of your plan description in your Keymetric's __Settings__ tab).

Please in the future consider posting Keymetrics related issues [here](https://github.com/Unitech/keymetrics.io/issues).
