### ISSUE TITLE
How to set a new probe to the Dashboard

### ISSUE THREAD

**Issue by efkan** [keymetrics/pmx#20]
Hello,

I have a 'free plan' account. 
I've added below codes. I can see on Probes debug page. However, I wasn't able to put my probe on my Dashboard. Actually I don't know whether I can see on my dashboard or not. What should I do?

    var pmx = require('pmx'),
        probe = pmx.probe(),
        meter = probe.meter({ name: 'req/min', agg_type: 'avg', seconds: 60 });
    app.use(function(req, res, next){ meter.mark() })
    pmx.init()

**Comment by jshkurti** [comment]
Try this way : 
```javascript
var pmx = require('pmx').init(),
    probe = pmx.probe(),
    meter = probe.meter({ name: 'req/min', agg_type: 'avg', seconds: 60 });
app.use(function(req, res, next){ meter.mark() })
```

Oh, also, requiring pmx should be the first thing you do in your code, it should be before any other require().

**Comment by efkan** [comment]
Thank you,

Actually I've been editing my question :) You are quicker than me!

Can I use a meter as `probe.meter({ name: 'req/min', agg_type: 'sum', seconds: 36000 })` ?
Sorry, I couldn't find `aggr_type: 'sum'` within the codes. 
It could be working with only 'avg'?

https://github.com/keymetrics/pmx/blob/master/lib/utils/probes/Meter.js#L13

**Comment by efkan** [comment]
Actually I intend to see my API request count by hour. Is there any chance?

**Comment by jshkurti** [comment]
Does it work ? By setting seconds to 3600 ?

**Comment by efkan** [comment]
No, actually it doesn't work.

**Comment by efkan** [comment]
I understand. I cannot use `pmx` to log API request by ten minutes or hour.
