### ISSUE TITLE
Can't get the latency working with node cluster

### ISSUE THREAD

**Issue by DavzorD** [keymetrics/pmx#24]
Hey,

i'm trying to use pm2 with pmx but I can't get the HTTP Latency working. (Basically, no routes are working)

I use node-cluster to spawn 4 processes.
var pmx = require('pmx').init();
is the first line of my program and I spawn the different processes after.

Any suggestions ?

**Comment by jorge-d** [comment]
Hi,

Only routes with latency over 200ms and response codes greater than or equal to 500 are logged by default.
You can change this using these params in your `pmx.init()`:
```javascript
{
    http_latency  : 200, // value in ms
    http_code     : 500, // All transactions wherehttp_code > 500 will be saved
}
```

**Comment by jshkurti** [comment]
Did this answer help ?

**Comment by Unitech** [comment]
use PM2 instead of building your own cluster logic, everythin will work as expected
