### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by inDream** [keymetrics/pmx#27]
Can I emit data with not ascii string?
When I try to emit data with Chinese, the text has converted to `-°`.

**Comment by Unitech** [comment]
https://nodejs.org/api/punycode.html

**Comment by inDream** [comment]
@Unitech Is this is the only solution for unicode?

**Comment by Unitech** [comment]
Will be fixed in the new PM2 + Keymetrics version. Now the transfer in is utf-8 mode

**Comment by inDream** [comment]
Thanks for your update.
