### ISSUE TITLE
NPM install isn't pulling in the fixes from commit d166b2aa960d04bbf994ea1999e3a72f951cb151

### ISSUE THREAD

**Issue by stringbeans** [keymetrics/pmx#29]
This specific fix addresses the circular JSON error. I'd like to pull in this fix however npm install doesn't bring these fixes in

**Comment by jorge-d** [comment]
The new version wasn't pushed on npm yet, you can use ` "pmx": "juggy/keymetrics/pmx/"` in your `package.json` or wait for the new release

**Comment by Unitech** [comment]
published 0.3.15
