### ISSUE TITLE
Remote action - restrict access.

### ISSUE THREAD

**Issue by stefan1968** [keymetrics/pmx#33]
Remote actions, are cool. I want to give some of my bosses access to the KeyMetrics page, but i'm uncomfortable with them having access to remote acttions and being able to restart the server. Something they might hit accidentally. I've tried changing them from 'Admin' to 'User' and 'Developer' but it doesn't restrict their access. Is there a way i can restrict access to via a user type, so they can't invoke remote actions or restart the server?

**Comment by jorge-d** [comment]
Hi,

If you set them as `user` they shouldn't be able to trigger any action, however the button does appear indeed. But hitting hit would return an "Unauthorized" error
