### ISSUE TITLE
Remote actionas allways return {success : true}

### ISSUE THREAD

**Issue by rafinskipg** [keymetrics/pmx#35]
I am using pm2 0.14.0 and pmx 0.3.17

Seeing this example :
```
pmx.action('get:phrases', { comment : 'Return all the phrases' }, function(reply) {
  reply({phrases : phrases});
});
```

On the console of keymetrics I am inspectionating the response for the remote action and I'm only getting this response : 

```
{ success : true }
```

**Comment by jshkurti** [comment]
Just tried this :
```js
var pmx = require('pmx');

pmx.action('foo:bar', { comment : 'Return all the foo bars' }, function(reply) {
  reply({'foo' : 'bar'});
});
```
It worked perfectly :
![foo](https://cloud.githubusercontent.com/assets/7647602/8306876/a1f94d1a-19bb-11e5-9327-02e6e27f8df4.png)

**Comment by jshkurti** [comment]
pmx@0.3.18 here

**Comment by rafinskipg** [comment]
After doing a `pm2 link stop` and `pm2 link start` it solved, the bug should be there :) 

thanks

**Comment by jshkurti** [comment]
Yeah you probably had an old version of the Keymetrica agent running in memory :)
