### ISSUE TITLE
[PMX] Action stop data stream will be binded once linked to Keymetrics

### ISSUE THREAD

**Issue by rbarkas** [keymetrics/pmx#36]
I've had a PMX action running ok for several months,but just today I started seeing the messages above.  When this occurs it screws up my program as it seems to execute and set okToStream false which causes the task fail.

The code I use is:

    pmx.action('stop data stream', function (reply) {
        okToStream = false;
        reply("Data stream stopped");
    });

What does the error message mean?

**Comment by jshkurti** [comment]
What error message ?

**Comment by rbarkas** [comment]
The one in the issue title:

PMX] Action stop data stream will be binded once linked to Keymetrics

**Comment by rbarkas** [comment]
Sorry, brain fart occurred.  Message appeared when the app is running outside of PM2.
My mistake.  I saw the error when I was running the app from the command line to debug another problem.

Looks like a genuine false alarm.  Please close the issue
