### ISSUE TITLE
user count with pmx

### ISSUE THREAD

**Issue by zerataul** [keymetrics/pmx#39]
hi

we are develop monitoring service.
we are testing many user connections.
our purpose about 7,000 user.

so, there is the bug.

some process not show user count, forever.
we are use with pmx.

why not show??
somebody help me, please.

under image link.
![_2015_07_02_11_19_36_25](https://cloud.githubusercontent.com/assets/681056/8468942/0b56cabe-20ae-11e5-98cc-b0f596894d9f.png)

**Comment by Unitech** [comment]
Fixed in https://github.com/Unitech/PM2/commit/ba1969ada8889f264139ada006fe39d06715a352

Available in development branch (npm install Unitech/pm2#development -g)

**Comment by zerataul** [comment]
Thank you!!
