### ISSUE TITLE
Alert system enhancement

### ISSUE THREAD

**Issue by Unitech** [keymetrics/pmx#44]
- [x] Implement thresold-avg that does exactly what the thresold do but based on an average (+ allow the average interval to be configurable)
- [x] Implement value configuration via Keymetrics
- [x] Implement alert thresold and thresold-avg on [counter](https://github.com/keymetrics/pmx#counter)

**Comment by alavit-d** [comment]
First test on [pm2-server-monit alert branch](https://github.com/pm2-hive/pm2-server-monit/tree/alert) using module_conf values.

**Comment by Unitech** [comment]
great thanks!
