### ISSUE TITLE
Cannot send optional data in scoped action.

### ISSUE THREAD

**Issue by Meaglin** [keymetrics/pmx#47]
I don't see how i can send optional data from keymetrics to my server in scoped actions.

**Comment by alavit-d** [comment]
Hi, 
At the moment there is no way to send fata from the dashboard. We are currently working on it.

**Comment by rodneytamblyn** [comment]
+1 for this

**Comment by Meaglin** [comment]
What is the status on this ?

The current docs say that it is possible: http://docs.keymetrics.io/docs/pages/custom-actions/

**Comment by Meaglin** [comment]
@Unitech Why is this closed?
