### ISSUE TITLE
conf.module_conf.password not correct value in module

### ISSUE THREAD

**Issue by natelaws** [keymetrics/pmx#48]
Within pm2 modules (such as pm2-mysql) it uses `conf.module_conf.password` which is set to "Password hidden" instead of the actual conf value.

Should these modules being use `conf.password` or should the hiddent text not be set by pmx?

**Comment by Unitech** [comment]
Thanks for reporting,

When you install pm2-mysql, is the password field in Keymetrics empty?
Once you set a password, the password is then hidden from the keymetrics interface (PM2 replace your password with "Password hidden")

**Comment by natelaws** [comment]
Yes, that is what the keymetrics interface looks like.  When updating it does look like it is sending the correct value.  On the server it also shows the correct password when using `pm2 get`.

I just put a `console.log(conf)` in the module and it shows me the "Password hidden" text there.
