### ISSUE TITLE
BUG: pmx lib transaction

### ISSUE THREAD

**Issue by frank-dspeed** [keymetrics/pmx#50]
dscms-5 (err):     at Function.Module._load (module.js:310:12)
dscms-5 (err):     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
dscms-5 (err):     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:210:23
dscms-5 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
dscms-5 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1166:30
dscms-5 (err):     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:124:13)
dscms-5 (err): /usr/bin/nodejs:1
dscms-5 (err): (function (exports, require, module, __filename, __dirname) { ELF
dscms-5 (err):                                                               ^
dscms-5 (err): SyntaxError: Unexpected token ILLEGAL
dscms-5 (err):     at exports.runInThisContext (vm.js:73:16)
dscms-5 (err):     at Module._compile (module.js:443:25)
dscms-5 (err):     at Object.Module._extensions..js (module.js:478:10)
dscms-5 (err):     at Module.load (module.js:355:32)
dscms-5 (err):     at Function.Module._load (module.js:310:12)
dscms-5 (err):     at Function.<anonymous> (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
dscms-5 (err):     at /usr/lib/node_modules/pm2/lib/ProcessContainer.js:210:23
dscms-5 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:52:16
dscms-5 (err):     at /usr/lib/node_modules/pm2/node_modules/async/lib/async.js:1166:30
dscms-5 (err):     at WriteStream.<anonymous> (/usr/lib/node_modules/pm2/lib/Utility.js:124:13)

**Comment by Unitech** [comment]
You tried to start a binary in cluster mode right?

**Comment by frank-dspeed** [comment]
good question i think yes i don't used node index.js i used ./mycmd if you call that a binary but it was only a execute able in my point of view with #!/bin/env node

**Comment by frank-dspeed** [comment]
anyway the error dont happens any more on development branch of this pm2 modul that utils this pmx
