### ISSUE TITLE
Versioning module: set a git repo programmatically

### ISSUE THREAD

**Issue by pjmartorell** [keymetrics/pmx#60]
Hi, I have deployed an app on Heroku which uses PM2 as a module that programmatically starts my NodeJS app and communicates with keymetrics.io. I would like to enable the Versioning module of keymetrics.io but, as I know, it requires a .git repo in the folder of the app. Is there any way to programmatically specify the git repo to pull of? Thanks

**Comment by Unitech** [comment]
Hey, is the `git` command available via CLI in heroku hosts?

**Comment by pjmartorell** [comment]
Yes, `git` is installed on Heroku hosts, however I have the app deployed on it so I can't `git clone` from the repo in a "dirty" folder. What do you suggest?

**Comment by pjmartorell** [comment]
My idea was to deploy on Heroku using a 'Deploy to Heroku' button and make it easy for the user to upgrade or downgrade their app using the Versioning module, but I think this module it's not suitable for my use case.

I close the issue, thanks!
