### ISSUE TITLE
Usage without Keymetrics account?

### ISSUE THREAD

**Issue by kokujin** [keymetrics/pmx#74]
Can I create probes/ alerts using PMX without a Keymetrics account? Thanks

**Comment by vmarchaud** [comment]
You might create a PM2 module that listen for event send by pmx and handle yourself alerts.
There isn't any documentations on event so you will need to dive into pmx source code to do this

**Comment by vmarchaud** [comment]
I might have misunderstood, you can create probes and alerts without PM2 linked to Keymetrics, data will not be pushed to keymetrics, if you want to monitor them youself, see my answer above

**Comment by kokujin** [comment]
Maybe it would be better to explain what I intend to do.

I am using PM2 to manage few applications, my deployment script restarts PM2 and disconnects immediately. I would however, like to display information from PM2 on a route over HTTP in my application, a sort of "Admin" page. I thought it would be easier instead of using the PM2 module to programmatically access process information

**Comment by vmarchaud** [comment]
You could totally make a module that listen for event send by pmx and display them.
I suggest you to make a simple module that connect to the pm2 bus and listen for `axm:monitor` event.
